### PR TITLE
integration spec and n+1 problem

### PR DESCRIPTION
**Pull request by ChrispaixK**
# Blog app - integration specs for views and fix n+1 problems

In this PR We :
* Install Capybara 
* Write integration tests with Capybara
  *  Write integration tests for user index
  * Write integration tests for user show
  * Write integration tests for post index
  * Write integration tests for show page
* Secure app from n+1 problems

### CODE REVIEW

**Review by rloterh — CHANGES_REQUESTED** [review]
Hi Chrispaix, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- Integration test for views properly covered using _Rspec_ and _Capybara_

## Required Changes ♻️
- [x] Your app does not solves N+1 problem when fetching all posts and their comments for a user. An example of this in a `posts#index` action should be:
`@posts = @user.posts.includes(:comments)` instead of `@posts = @user.posts` 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

**You can also consider:**
- Kindly include details of the co-contributor(s) in your ReadMe.
Implementing the above change(s) will make your ReadMe/ repository stand out even better 😉

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ChrispaixK** [comment]
Thank you @rloterh , I appreciate

**Review by uwadonat — APPROVED** [review]
## Hi @Team!

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
### Highlights
- Professional readme file ✔️
- Good commit history ✔️
approval

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by ChrispaixK** [comment]
Thank you @uwadonat

**Pull request merged**
